name: PyTest
on: pull_request
jobs:
  pytest:
    name: Run the application's tests with PyTest
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
          pip install pytest pytest-django
      - name: Run PyTest
        run: |
          python -m pytest -v